import React from 'react'
import { Route, Switch } from 'react-router-dom'
import { Button, Grid, Link, Stack, Typography as T } from '@material-ui/core'

function Footer() {
  return (
    <Grid container minHeight="100%" spacing={0}>
      <Grid item xs={12} sm={9}>
        <Switch>
          <Route exact path="/">
            <T variant="body2" flexGrow={1} sx={{ mb: '1.5em' }}>
              Customize the Material UI theme in <code>src/theme.tsx</code>. The
              <Link href="/theme-samples" variant="subtitle2">
                {' '}
                samples
              </Link>{' '}
              page will show your changes as you go.
            </T>
          </Route>
          <Route>
            <Button href="/">Home</Button>
          </Route>
        </Switch>
      </Grid>
      <Grid item xs={12} sm={3}>
        <Stack flexGrow={1} alignItems="center" spacing={0.25}>
          <T variant="subtitle2">This template includes:</T>
          <Link
            href="https://next.material-ui.com/getting-started/usage/"
            variant="body2"
          >
            Material UI (v5 beta)
          </Link>
          <Link
            href="https://reactrouter.com/web/guides/quick-start"
            variant="body2"
          >
            React Router
          </Link>
          <Link
            href="https://www.typescriptlang.org/docs/handbook/2/basic-types.html"
            variant="body2"
          >
            Typescript
          </Link>
          <Link href="https://prettier.io/docs/en/editors.html" variant="body2">
            prettier.js
          </Link>
        </Stack>
        <T variant="subtitle2" sx={{ mt: '1.5em' }}>
          Generated by{' '}
          <Link href="/">
            <code>cra-template-puddlebyte</code>
          </Link>
        </T>
      </Grid>
    </Grid>
  )
}

export default Footer
