import React from 'react'
import { Route, Switch } from 'react-router-dom'
import { Box, Button, Link, Stack, Typography as T } from '@material-ui/core'

function Footer() {
  return (
    <Box minHeight="100%" display="flex">
      <Box
        display="flex"
        flexDirection="column"
        alignItems="flex-start"
        flexGrow={1}
      >
        <Switch>
          <Route exact path="/">
            <T variant="body2" flexGrow={1}>
              Customize the Material UI theme in <code>src/theme.tsx</code>. The
              <Link href="/theme-samples" variant="subtitle2">
                {' '}
                samples
              </Link>{' '}
              page will show your changes as you go.
            </T>
          </Route>
          <Route>
            <Button href="/">Home</Button>
          </Route>
        </Switch>
      </Box>
      <Box display="flex" flexDirection="column">
        <Stack flexGrow={1} alignItems="flex-end" spacing={0.5}>
          <T variant="subtitle2">This template includes:</T>
          <Link
            href="https://next.material-ui.com/getting-started/usage/"
            variant="body2"
          >
            Material UI (v5 beta)
          </Link>
          <Link
            href="https://reactrouter.com/web/guides/quick-start"
            variant="body2"
          >
            React Router
          </Link>
          <Link
            href="https://www.typescriptlang.org/docs/handbook/2/basic-types.html"
            variant="body2"
          >
            Typescript
          </Link>
          <Link href="https://prettier.io/docs/en/editors.html" variant="body2">
            prettier.js
          </Link>
        </Stack>
        <T variant="subtitle2">
          Generated by{' '}
          <Link>
            <code>cra-template-puddlebyte</code>
          </Link>
        </T>
      </Box>
    </Box>
  )
}

export default Footer
